---
title: "STATS 506 HW 2"
author: "Calder Moore"
format: pdf
editor: visual
---

# STATS 506 HW 2

## Problem 1 - Modified Random Walk

### a) (with loop)

```{r}
#' Random walk with loops. 50% chance of moving +-1, if +1 is chosen then a 5% chance of moving +10 rather than just +1, if -1 is chosen then a 20% chance of moving -3 rather than just -1.
#' @param count how many steps the random walk will take
#' @returns the final value once the steps are completed
random_walk1 <- function(count){
  walk <- 0
  for(i in 1:count){
    #take the initial sample for the +-1
    sample_1 <- sample(c(-1, 1), 1)
    #conditions for the extra possible +10 or -3 move
    if(sample_1 == 1){
      sample_2 <- sample(c(1, 10), size = 1, prob = c(0.95, 0.05))
      walk <- walk + sample_2
    }
    else{
      sample_3 <- sample(c(-1, -3), size = 1, prob = c(0.8, 0.2))
      walk <- walk + sample_3
    }
  }
  return(walk)
}
```

### a) (vectorized)

```{r}
#' Random walk vectorized. Same task as above, but vectorized rather than with loops. Does all steps and once and sums them.
#' @param count how many steps the random walk will take
#' @returns the final value once the steps are completed
random_walk2 <- function(count){
  walk <- 0
  #we can do all the steps at once, add them up, and add the total to walk. Need to include all possible outcomes and their respective probabilities. Replace needs to be true now since we aren't looping over the function each time anymore and need to be sampling from each of the 4 possibilities this time.
  all_steps <- sample(c(-1, 1, -3, 10), size = count, replace = TRUE, prob = c(4/10, 19/40, 1/10, 1/40))
  
  walk <- walk + sum(all_steps)
  
  return(walk)
}
```



```{r}
#| echo: false
2 * 2
```


